---
- name: install php-fpm
  apt: 
    name: php-fpm 
    update_cache: yes 
    state: latest

- name: configure php-fpm.conf
  copy:
    dest: /etc/zabbix/php-fpm.conf
    src: "templates/zabbix_php-fpm.j2"

- name: install rights to zabbix.sock
  file:
    name: /run/php/zabbix.sock
    mode: '1777'

  notify:
    - enable php7.4-fpm
    - start php7.4-fpm

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
...