---
- name: remove Zabbix repo deb
  apt_repository:
    repo: deb "{{ zabbix_repo_deb }}"
    state: absent

- name: download Zabbix repo deb
  get_url:
    url: "{{ zabbix_repo_deb }}"
    dest: "{{ zabbix_repo_local_deb }}"

- name: install Zabbix repo deb
  apt:
    deb: "{{ zabbix_repo_local_deb }}"
    state: present
    
- name: install Zabbix
  apt:
    name:
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    - zabbix-agent2
    state: present
    update_cache: yes
    
- name: remove Apache
  apt:
    name: 
      - apache2
    state: absent
    autoclean: yes
    autoremove: yes
    
  
  notify:
    - enable zabbix
    - start zabbix
...
