---
- name: remove Zabbix repo deb
  apt_repository:
    repo: deb "{{ zabbix_repo_deb }}"
    state: absent

- name: download Zabbix repo deb
  get_url:
    url: "{{ zabbix_repo_deb }}"
    dest: "{{ zabbix_repo_local_deb }}"

- name: install Zabbix repo deb
  apt:
    deb: "{{ zabbix_repo_local_deb }}"
    state: present
    
- name: install Zabbix
  apt:
    name:
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    - zabbix-agent2
    state: present
    update_cache: yes
    
- name: remove Apache
  apt:
    name: 
      - apache2
    state: absent
    autoclean: yes
    autoremove: yes
    
  notify:
    - enable zabbix
    - start zabbix

- name: configure zabbix_server.conf
  copy:
    dest: /etc/nginx/conf.d/zabbix.conf
    src: "templates/zabbix_nginx.j2"

- name: path to server.sql.gz
  stat:
      path: /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
  register: gz_in_place

- name: unpack server.sql.gz
  command:
    gzip -d /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz
  when: gz_in_place.stat.exists

- name: fill db
  become_user: postgres
  postgresql_db:
    name: zabbix
    state: restore
    target: /usr/share/zabbix-sql-scripts/postgresql/server.sql

- name: grant all to zabbix
  postgresql_privs:
    db: zabbix
    state: present
    objs: ALL_IN_SCHEMA
    privs: ALL
    roles: zabbix
    grant_option: yes
  become_user: postgres


- name: disable default configure
  command: mv /etc/zabbix/zabbix_server.conf /etc/zabbix/zabbix_server.conf.disabled
  failed_when: false

- name: configure zabbix_server.conf
  copy:
    dest: /etc/zabbix/zabbix_server.conf
    src: "templates/zabbix_server_conf.j2"

- name:  configure zabbix gui configure
  copy:
    dest: /etc/zabbix/web/zabbix.conf.php
    src: "templates/zabbix_gui_config.j2" 

  notify:
    - restart zabbix
  
...
