---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: start nginx
  systemd:
    name: nginx
    state: started

- name: stop nginx
  systemd:
    name: nginx
    state: stopped

- name: enable nginx
  systemd:
    name: nginx
    enabled: yes
...
