---
- name: add Postgres repo
  command: |
    sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: download PGP-key
  get_url:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      dest: /etc/ACCC4CF8.asc

- name: install PGP-key
  apt_key:
      file: /etc/ACCC4CF8.asc 
      state: present

- name: install postgres
  apt:
    name:
    - postgresql-14
    - php7.4-pgsql
    update_cache: yes
  
  notify:
    - enable postgresql
    - start postgresql
...
