---
- name: add postgres repo
  command: |
    sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

- name: download PGP-key
  get_url:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      dest: /etc/ACCC4CF8.asc

- name: install PGP-key
  apt_key:
      file: /etc/ACCC4CF8.asc 
      state: present

- name: install postgres
  apt:
    name:
    - postgresql-14
    - php7.4-pgsql
    update_cache: yes

- name: configure postgres
  copy:
    dest: /etc/postgresql/14/main/pg_hba.conf
    src: "templates/zabbix_pg.j2"
  
  notify:
    - enable postgresql
    - start postgresql

- name: drop db
  postgresql_db:
    name: zabbix
    state: absent
  become_user: postgres

- name: create role
  postgresql_user:
    user: zabbix
    password: zabbix
    role_attr_flags: CREATEDB,NOSUPERUSER
    state: present
  become_user: postgres  

- name: create db
  postgresql_db:
    name: zabbix
    encoding: UTF-8
    owner: zabbix
    state: present
  become_user: postgres

  notify:
    - restart postgresql
  
...
