---

- name: Update apt repo and cache
  apt: 
    update_cache: yes 
    force_apt_get: yes 
    cache_valid_time: 3600

- name: Upgrade all packages
  apt: 
   upgrade: dist 
   force_apt_get: yes

- name: Install soft
  apt:
    name: "{{ item }}"
  loop:
    - nano
    - curl 
    - bind9-utils 
    - wget 
    - net-tools 
    - traceroute 
    - git 
    - tcpdump 
    - rsync 
    - mlocate 
    - htop 
    - tar
    - gzip
    - zip 
    - unzip 
    - gnupg2
    - python3-psycopg2
    - acl
    - gnupg
    - postgresql-common
    - apt-transport-https
    - lsb-release
    #- python3-pip
  

...
