---

- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt: 
    update_cache: yes 
    force_apt_get: yes 
    cache_valid_time: 3600

- name: Upgrade all packages on servers
  apt: 
   upgrade: dist 
   force_apt_get: yes

- name: Install soft
  apt:
    name: "{{ item }}"
  loop:
    - nano
    - curl 
    - bind9-utils 
    - wget 
    - net-tools 
    - traceroute 
    - git 
    - tcpdump 
    - rsync 
    - mlocate 
    - htop 
    - tar 
    - zip 
    - unzip 
    - gnupg2

...
